apiVersion: v1
kind: ConfigMap
metadata:
  name: industrial-datagen-config
  labels:
    app.kubernetes.io/name: industrial-datagen
data:
  INDGEN_DEBUG: "false"
  INDGEN_STORAGE_BACKEND: memory
  INDGEN_CORS_ORIGINS: '["*"]'
  INDGEN_STATIC_DIR: /app/static
